feat: original owner & all addresses of paws
OtterClam/otter-contracts pull request #6
Opened 2022-01-11 10:50 UTC by d0c0q

2022-01-13 15:23 UTC, otterclamking commented on contracts/OtterPAWBondStakeDepository.sol
> +    function addDiscountTerms(
```suggestion
    function addDiscountTerm(
```

2022-01-13 15:23 UTC, otterclamking commented on contracts/OtterPAWBondStakeDepository.sol
> +    mapping(address => mapping(uint256 => address)) public pawOwners;
Looks like you replace paw with nft, so we could replace all paw to nft

```suggestion
    mapping(address => mapping(uint256 => address)) public nftOwners;
```

2022-01-13 15:23 UTC, otterclamking commented on contracts/OtterPAWBondStakeDepository.sol
> +                discountTerms[_nft].discount != 0 &&
why need to check this?

2022-01-13 15:41 UTC, d0c0q commented on contracts/OtterPAWBondStakeDepository.sol
> +                discountTerms[_nft].discount != 0 &&
addDiscountTerm(address, discount, 0) means getting endEpoch from note

2022-01-13 15:45 UTC, d0c0q commented on contracts/OtterPAWBondStakeDepository.sol
> +    function addDiscountTerms(
ac7581019fccaa2a52bbbd7c3cc2bd47d4156b13

2022-01-13 15:51 UTC, d0c0q commented on contracts/OtterPAWBondStakeDepository.sol
> +    mapping(address => mapping(uint256 => address)) public pawOwners;
https://github.com/OtterClam/otter-contracts/pull/6/commits/64fa641d63625e784265156f211f74fa4d938a52

2022-01-17 14:37 UTC, otterclamking requested changes

2022-01-17 14:37 UTC, otterclamking commented on scripts/deployPAWBond.js
> +      name: 'SAFE_HAND_180DAY_NOTE',
no discount for safe hand note

2022-01-17 14:44 UTC, d0c0q commented on scripts/deployPAWBond.js
> +      name: 'SAFE_HAND_180DAY_NOTE',
https://github.com/OtterClam/otter-contracts/pull/6/commits/cf18a0fa9f54f54590d247bc2e75736c2304e606

2022-01-17 14:44 UTC, d0c0q commented on contracts/OtterPAWBondStakeDepository.sol
> +    mapping(address => mapping(uint256 => address)) public nftOwners;
https://github.com/OtterClam/otter-contracts/pull/6/commits/7901075d3b9153e4e67f9c221f9d9c6d1028fb4a

2022-01-20 11:41 UTC, merged